name: Build website
on:
  [push, pull_request]

jobs:
  build_website:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: 18
      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-18-16-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-18-16-yarn-
      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Build
        run: yarn workspace website run build
